<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rishikumar Mathiazhagan">
<meta name="dcterms.date" content="2025-04-23">

<title>A Replication of Karlan and List (2007) – Rishi’s Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Rishi’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#description" id="toc-description" class="nav-link" data-scroll-target="#description">Description</a></li>
  <li><a href="#balance-test" id="toc-balance-test" class="nav-link" data-scroll-target="#balance-test">Balance Test</a></li>
  </ul></li>
  <li><a href="#experimental-results" id="toc-experimental-results" class="nav-link" data-scroll-target="#experimental-results">Experimental Results</a>
  <ul class="collapse">
  <li><a href="#charitable-contribution-made" id="toc-charitable-contribution-made" class="nav-link" data-scroll-target="#charitable-contribution-made">Charitable Contribution Made</a></li>
  <li><a href="#interpretation-of-probit-regression-result" id="toc-interpretation-of-probit-regression-result" class="nav-link" data-scroll-target="#interpretation-of-probit-regression-result">Interpretation of Probit Regression Result</a></li>
  <li><a href="#differences-between-match-rates" id="toc-differences-between-match-rates" class="nav-link" data-scroll-target="#differences-between-match-rates">Differences between Match Rates</a></li>
  <li><a href="#effectiveness-of-different-match-ratios-t-test-results" id="toc-effectiveness-of-different-match-ratios-t-test-results" class="nav-link" data-scroll-target="#effectiveness-of-different-match-ratios-t-test-results">Effectiveness of Different Match Ratios: T-Test Results</a></li>
  <li><a href="#regression-analysis-impact-of-match-ratio-on-donation-behavior" id="toc-regression-analysis-impact-of-match-ratio-on-donation-behavior" class="nav-link" data-scroll-target="#regression-analysis-impact-of-match-ratio-on-donation-behavior">Regression Analysis: Impact of Match Ratio on Donation Behavior</a></li>
  <li><a href="#match-ratio-differences-response-rate-and-regression-analysis" id="toc-match-ratio-differences-response-rate-and-regression-analysis" class="nav-link" data-scroll-target="#match-ratio-differences-response-rate-and-regression-analysis">Match Ratio Differences: Response Rate and Regression Analysis</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#size-of-charitable-contribution" id="toc-size-of-charitable-contribution" class="nav-link" data-scroll-target="#size-of-charitable-contribution">Size of Charitable Contribution</a></li>
  <li><a href="#effect-of-match-offers-on-donation-amounts" id="toc-effect-of-match-offers-on-donation-amounts" class="nav-link" data-scroll-target="#effect-of-match-offers-on-donation-amounts">Effect of Match Offers on Donation Amounts</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#conditional-effect-of-treatment-on-donation-amount-among-donors-only" id="toc-conditional-effect-of-treatment-on-donation-amount-among-donors-only" class="nav-link" data-scroll-target="#conditional-effect-of-treatment-on-donation-amount-among-donors-only">Conditional Effect of Treatment on Donation Amount (Among Donors Only)</a></li>
  <li><a href="#donation-amount-distributions-treatment-vs.-control-donors-only" id="toc-donation-amount-distributions-treatment-vs.-control-donors-only" class="nav-link" data-scroll-target="#donation-amount-distributions-treatment-vs.-control-donors-only">Donation Amount Distributions: Treatment vs.&nbsp;Control (Donors Only)</a></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1">Interpretation</a></li>
  </ul></li>
  <li><a href="#simulation-experiment" id="toc-simulation-experiment" class="nav-link" data-scroll-target="#simulation-experiment">Simulation Experiment</a>
  <ul class="collapse">
  <li><a href="#law-of-large-numbers" id="toc-law-of-large-numbers" class="nav-link" data-scroll-target="#law-of-large-numbers">Law of Large Numbers</a></li>
  <li><a href="#simulating-the-law-of-large-numbers" id="toc-simulating-the-law-of-large-numbers" class="nav-link" data-scroll-target="#simulating-the-law-of-large-numbers">Simulating the Law of Large Numbers</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central Limit Theorem</a></li>
  <li><a href="#sampling-distributions-at-different-sample-sizes" id="toc-sampling-distributions-at-different-sample-sizes" class="nav-link" data-scroll-target="#sampling-distributions-at-different-sample-sizes">Sampling Distributions at Different Sample Sizes</a></li>
  <li><a href="#what-we-learn" id="toc-what-we-learn" class="nav-link" data-scroll-target="#what-we-learn">What We Learn</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Replication of Karlan and List (2007)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rishikumar Mathiazhagan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 23, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Dean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the <em>American Economic Review</em> in 2007. The article and supporting data are available from the <a href="https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774">AEA website</a> and from Innovations for Poverty Action as part of <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&amp;version=4.2">Harvard’s Dataverse</a>.</p>
<p>To better understand the demand side of charitable giving, Karlan and List used a natural field experiment involving over 50,000 previous donors to a politically liberal nonprofit organization. The letters were randomized to test three main dimensions: whether a matching grant was offered, the ratio of the match (1:1, 2:1, or 3:1), and the size of the matching fund ($25,000, $50,000, $100,000, or unstated). In addition, suggested donation amounts were varied using multipliers of the recipient’s previous highest contribution. Their findings revealed that simply offering a match significantly increased both the likelihood of donating and the average amount raised per letter. However, increasing the match ratio beyond 1:1 did not yield additional benefits, challenging conventional fundraising wisdom. Notably, the effect of matching offers was more pronounced in conservative-leaning (“red”) states, suggesting that political context may shape donor responsiveness.</p>
<p>This project seeks to replicate their results.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="description" class="level3">
<h3 class="anchored" data-anchor-id="description">Description</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 50,083
Columns: 51
$ treatment          &lt;dbl&gt; 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, …
$ control            &lt;dbl&gt; 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, …
$ ratio              &lt;dbl+lbl&gt; 0, 0, 1, 1, 1, 0, 1, 2, 2, 1, 1, 2, 0, 2, 0, 1,…
$ ratio2             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, …
$ ratio3             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, …
$ size               &lt;dbl+lbl&gt; 0, 0, 3, 4, 2, 0, 1, 3, 4, 1, 4, 2, 0, 1, 0, 4,…
$ size25             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, …
$ size50             &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, …
$ size100            &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ sizeno             &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, …
$ ask                &lt;dbl+lbl&gt; 0, 0, 1, 1, 1, 0, 3, 3, 2, 2, 1, 3, 0, 2, 0, 1,…
$ askd1              &lt;dbl&gt; 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, …
$ askd2              &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, …
$ askd3              &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, …
$ ask1               &lt;dbl&gt; 55, 25, 55, 55, 35, 95, 125, 75, 250, 150, 125, 25,…
$ ask2               &lt;dbl&gt; 70, 35, 70, 70, 45, 120, 160, 95, 315, 190, 160, 35…
$ ask3               &lt;dbl&gt; 85, 50, 85, 85, 55, 145, 190, 120, 375, 225, 190, 5…
$ amount             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ gave               &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ amountchange       &lt;dbl&gt; -45, -25, -50, -25, -15, -45, -50, -65, -100, -125,…
$ hpa                &lt;dbl&gt; 45, 25, 50, 50, 25, 90, 100, 65, 200, 125, 100, 5, …
$ ltmedmra           &lt;dbl&gt; 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, …
$ freq               &lt;dbl&gt; 2, 2, 3, 15, 42, 20, 12, 13, 28, 4, 1, 1, 2, 80, 3,…
$ years              &lt;dbl&gt; 4, 3, 2, 8, 95, 10, 8, 16, 19, 7, 3, 1, 6, 19, 3, 1…
$ year5              &lt;dbl&gt; 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, …
$ mrm2               &lt;dbl&gt; 31, 5, 6, 1, 24, 3, 4, 4, 6, 35, 41, 8, 28, 15, 5, …
$ dormant            &lt;dbl&gt; 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, …
$ female             &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, …
$ couple             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ state50one         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ nonlit             &lt;dbl&gt; 5, 0, 3, 1, 1, 0, 0, 4, 1, 4, 4, 1, 1, 4, 0, 3, 6, …
$ cases              &lt;dbl&gt; 4, 2, 1, 2, 1, 0, 1, 3, 1, 3, 3, 2, 1, 1, 1, 1, 2, …
$ statecnt           &lt;dbl&gt; 4.5002995, 2.9822462, 9.6070213, 3.2814682, 2.30201…
$ stateresponse      &lt;dbl&gt; 0.01994681, 0.02608696, 0.02304817, 0.02066869, 0.0…
$ stateresponset     &lt;dbl&gt; 0.019502353, 0.027833002, 0.022158911, 0.024702653,…
$ stateresponsec     &lt;dbl&gt; 0.020806242, 0.022494888, 0.024743512, 0.012681159,…
$ stateresponsetminc &lt;dbl&gt; -0.001303889, 0.005338114, -0.002584601, 0.01202149…
$ perbush            &lt;dbl&gt; 0.4900000, 0.4646465, 0.4081633, 0.4646465, 0.52525…
$ close25            &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, …
$ red0               &lt;dbl&gt; 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, …
$ blue0              &lt;dbl&gt; 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, …
$ redcty             &lt;dbl&gt; 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, …
$ bluecty            &lt;dbl&gt; 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, …
$ pwhite             &lt;dbl&gt; 0.4464934, NA, 0.9357064, 0.8883309, 0.7590141, 0.8…
$ pblack             &lt;dbl&gt; 0.527769208, NA, 0.011948366, 0.010760401, 0.127420…
$ page18_39          &lt;dbl&gt; 0.3175913, NA, 0.2761282, 0.2794118, 0.4423889, 0.3…
$ ave_hh_sz          &lt;dbl&gt; 2.10, NA, 2.48, 2.65, 1.85, 2.92, 2.10, 2.47, 2.49,…
$ median_hhincome    &lt;dbl&gt; 28517, NA, 51175, 79269, 40908, 61779, 54655, 14152…
$ powner             &lt;dbl&gt; 0.4998072, NA, 0.7219406, 0.9204314, 0.4160721, 0.9…
$ psch_atlstba       &lt;dbl&gt; 0.32452780, NA, 0.19266793, 0.41214216, 0.43996516,…
$ pop_propurban      &lt;dbl&gt; 1.0000000, NA, 1.0000000, 1.0000000, 1.0000000, 0.9…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dfSummary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data Frame Summary  
data  
Dimensions: 50083 x 51  
Duplicates: 30  

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
No   Variable             Label                                      Stats / Values                  Freqs (% of Valid)      Graph                  Valid      Missing  
---- -------------------- ------------------------------------------ ------------------------------- ----------------------- ---------------------- ---------- ---------
1    treatment            Treatment                                  Min  : 0                        0 : 16687 (33.3%)       IIIIII                 50083      0        
     [numeric]                                                       Mean : 0.7                      1 : 33396 (66.7%)       IIIIIIIIIIIII          (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

2    control              Control                                    Min  : 0                        0 : 33396 (66.7%)       IIIIIIIIIIIII          50083      0        
     [numeric]                                                       Mean : 0.3                      1 : 16687 (33.3%)       IIIIII                 (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

3    ratio                Match ratio                                Mean (sd) : 1.3 (1.2)           0 : 16687 (33.3%)       IIIIII                 50083      0        
     [haven_labelled,                                                min &lt; med &lt; max:                1 : 11133 (22.2%)       IIII                   (100.0%)   (0.0%)   
     vctrs_vctr,                                                     0 &lt; 1 &lt; 3                       2 : 11134 (22.2%)       IIII                                       
     double]                                                         IQR (CV) : 2 (0.9)              3 : 11129 (22.2%)       IIII                                       

4    ratio2               2:1 match ratio                            Min  : 0                        0 : 38949 (77.8%)       IIIIIIIIIIIIIII        50083      0        
     [numeric]                                                       Mean : 0.2                      1 : 11134 (22.2%)       IIII                   (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

5    ratio3               3:1 match ratio                            Min  : 0                        0 : 38954 (77.8%)       IIIIIIIIIIIIIII        50083      0        
     [numeric]                                                       Mean : 0.2                      1 : 11129 (22.2%)       IIII                   (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

6    size                 Match threshold                            1. [0] Control                  16687 (33.3%)           IIIIII                 50083      0        
     [haven_labelled,                                                2. [1] $25,000                   8350 (16.7%)           III                    (100.0%)   (0.0%)   
     vctrs_vctr,                                                     3. [2] $50,000                   8345 (16.7%)           III                                        
     double]                                                         4. [3] $100,000                  8350 (16.7%)           III                                        
                                                                     5. [4] Unstated                  8351 (16.7%)           III                                        

7    size25               $25,000 match threshold                    Min  : 0                        0 : 41733 (83.3%)       IIIIIIIIIIIIIIII       50083      0        
     [numeric]                                                       Mean : 0.2                      1 :  8350 (16.7%)       III                    (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

8    size50               $50,000 match threshold                    Min  : 0                        0 : 41738 (83.3%)       IIIIIIIIIIIIIIII       50083      0        
     [numeric]                                                       Mean : 0.2                      1 :  8345 (16.7%)       III                    (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

9    size100              $100,000 match threshold                   Min  : 0                        0 : 41733 (83.3%)       IIIIIIIIIIIIIIII       50083      0        
     [numeric]                                                       Mean : 0.2                      1 :  8350 (16.7%)       III                    (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

10   sizeno               Unstated match threshold                   Min  : 0                        0 : 41732 (83.3%)       IIIIIIIIIIIIIIII       50083      0        
     [numeric]                                                       Mean : 0.2                      1 :  8351 (16.7%)       III                    (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

11   ask                  Suggested donation amount                  1. [0] Control                  16687 (33.3%)           IIIIII                 50083      0        
     [haven_labelled,                                                2. [1] 1x                       11134 (22.2%)           IIII                   (100.0%)   (0.0%)   
     vctrs_vctr,                                                     3. [2] 1.25x                    11133 (22.2%)           IIII                                       
     double]                                                         4. [3] 1.50x                    11129 (22.2%)           IIII                                       

12   askd1                Suggested donation was highest previous    Min  : 0                        0 : 38949 (77.8%)       IIIIIIIIIIIIIII        50083      0        
     [numeric]            contribution                               Mean : 0.2                      1 : 11134 (22.2%)       IIII                   (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

13   askd2                Suggested donation was 1.25 x highest      Min  : 0                        0 : 38950 (77.8%)       IIIIIIIIIIIIIII        50083      0        
     [numeric]            previous contribution                      Mean : 0.2                      1 : 11133 (22.2%)       IIII                   (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

14   askd3                Suggested donation was 1.50 x highest      Min  : 0                        0 : 38954 (77.8%)       IIIIIIIIIIIIIII        50083      0        
     [numeric]            previous contribution                      Mean : 0.2                      1 : 11129 (22.2%)       IIII                   (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

15   ask1                 Highest previous contribution (for         Mean (sd) : 71.5 (101.7)        18 distinct values      :                      50083      0        
     [numeric]            suggestion)                                min &lt; med &lt; max:                                        :                      (100.0%)   (0.0%)   
                                                                     25 &lt; 45 &lt; 1500                                          :                                          
                                                                     IQR (CV) : 30 (1.4)                                     :                                          
                                                                                                                             :                                          

16   ask2                 1.25 x highest previous contribution       Mean (sd) : 91.8 (127.3)        18 distinct values      :                      50083      0        
     [numeric]            (for suggestion)                           min &lt; med &lt; max:                                        :                      (100.0%)   (0.0%)   
                                                                     35 &lt; 60 &lt; 1875                                          :                                          
                                                                     IQR (CV) : 40 (1.4)                                     :                                          
                                                                                                                             :                                          

17   ask3                 1.50 x highest previous contribution       Mean (sd) : 111 (151.7)         18 distinct values      :                      50083      0        
     [numeric]            (for suggestion)                           min &lt; med &lt; max:                                        :                      (100.0%)   (0.0%)   
                                                                     50 &lt; 70 &lt; 2250                                          :                                          
                                                                     IQR (CV) : 45 (1.4)                                     :                                          
                                                                                                                             :                                          

18   amount               Dollars given                              Mean (sd) : 0.9 (8.7)           43 distinct values      :                      50083      0        
     [numeric]                                                       min &lt; med &lt; max:                                        :                      (100.0%)   (0.0%)   
                                                                     0 &lt; 0 &lt; 400                                             :                                          
                                                                     IQR (CV) : 0 (9.5)                                      :                                          
                                                                                                                             :                                          

19   gave                 Gave anything                              Min  : 0                        0 : 49049 (97.9%)       IIIIIIIIIIIIIIIIIII    50083      0        
     [numeric]                                                       Mean : 0                        1 :  1034 ( 2.1%)                              (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

20   amountchange         Change in amount given                     Mean (sd) : -52.7 (1267.2)      240 distinct values                       :    50083      0        
     [numeric]                                                       min &lt; med &lt; max:                                                          :    (100.0%)   (0.0%)   
                                                                     -200412.1 &lt; -30 &lt; 275                                                     :                        
                                                                     IQR (CV) : 25 (-24.1)                                                     :                        
                                                                                                                                               :                        

21   hpa                  Highest previous contribution              Mean (sd) : 59.4 (71.2)         243 distinct values     :                      50083      0        
     [numeric]                                                       min &lt; med &lt; max:                                        :                      (100.0%)   (0.0%)   
                                                                     0 &lt; 45 &lt; 1000                                           :                                          
                                                                     IQR (CV) : 30 (1.2)                                     :                                          
                                                                                                                             : .                                        

22   ltmedmra             Small prior donor: last gift was less      Min  : 0                        0 : 25356 (50.6%)       IIIIIIIIII             50083      0        
     [numeric]            than median $35                            Mean : 0.5                      1 : 24727 (49.4%)       IIIIIIIII              (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

23   freq                 Number of prior donations                  Mean (sd) : 8 (11.4)            144 distinct values     :                      50083      0        
     [numeric]                                                       min &lt; med &lt; max:                                        :                      (100.0%)   (0.0%)   
                                                                     0 &lt; 4 &lt; 218                                             :                                          
                                                                     IQR (CV) : 8 (1.4)                                      :                                          
                                                                                                                             : .                                        

24   years                Number of years since initial donation     Mean (sd) : 6.1 (5.5)           22 distinct values      :                      50082      1        
     [numeric]                                                       min &lt; med &lt; max:                                        :                      (100.0%)   (0.0%)   
                                                                     0 &lt; 5 &lt; 95                                              :                                          
                                                                     IQR (CV) : 7 (0.9)                                      : .                                        
                                                                                                                             : :                                        

25   year5                At least 5 years since initial donation    Min  : 0                        0 : 24600 (49.1%)       IIIIIIIII              50083      0        
     [numeric]                                                       Mean : 0.5                      1 : 25483 (50.9%)       IIIIIIIIII             (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

26   mrm2                 Number of months since last donation       Mean (sd) : 13 (12.1)           67 distinct values      :                      50082      1        
     [numeric]                                                       min &lt; med &lt; max:                                        :                      (100.0%)   (0.0%)   
                                                                     0 &lt; 8 &lt; 168                                             :                                          
                                                                     IQR (CV) : 15 (0.9)                                     : .                                        
                                                                                                                             : : .                                      

27   dormant              Already donated in 2005                    Min  : 0                        0 : 23866 (47.7%)       IIIIIIIII              50083      0        
     [numeric]                                                       Mean : 0.5                      1 : 26217 (52.3%)       IIIIIIIIII             (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

28   female               Female                                     Min  : 0                        0 : 35374 (72.2%)       IIIIIIIIIIIIII         48972      1111     
     [numeric]                                                       Mean : 0.3                      1 : 13598 (27.8%)       IIIII                  (97.8%)    (2.2%)   
                                                                     Max  : 1                                                                                           

29   couple               Couple                                     Min  : 0                        0 : 44438 (90.8%)       IIIIIIIIIIIIIIIIII     48935      1148     
     [numeric]                                                       Mean : 0.1                      1 :  4497 ( 9.2%)       I                      (97.7%)    (2.3%)   
                                                                     Max  : 1                                                                                           

30   state50one           State tag: 1 for one observation of each   Min  : 0                        0 : 50033 (99.9%)       IIIIIIIIIIIIIIIIIII    50083      0        
     [numeric]            of 50 states; 0 otherwise                  Mean : 0                        1 :    50 ( 0.1%)                              (100.0%)   (0.0%)   
                                                                     Max  : 1                                                                                           

31   nonlit               Nonlitigation                              Mean (sd) : 2.5 (2)             0 : 10873 (21.9%)       IIII                   49631      452      
     [numeric]                                                       min &lt; med &lt; max:                1 : 11944 (24.1%)       IIII                   (99.1%)    (0.9%)   
                                                                     0 &lt; 3 &lt; 6                       2 :  1163 ( 2.3%)                                                  
                                                                     IQR (CV) : 3 (0.8)              3 :  5148 (10.4%)       II                                         
                                                                                                     4 : 11557 (23.3%)       IIII                                       
                                                                                                     5 :  6835 (13.8%)       II                                         
                                                                                                     6 :  2111 ( 4.3%)                                                  

32   cases                Court cases from state in 2004-5 in        Mean (sd) : 1.5 (1.2)           0 : 10682 (21.5%)       IIII                   49631      452      
     [numeric]            which organization was involved            min &lt; med &lt; max:                1 : 17435 (35.1%)       IIIIIII                (99.1%)    (0.9%)   
                                                                     0 &lt; 1 &lt; 4                       2 :  9796 (19.7%)       III                                        
                                                                     IQR (CV) : 1 (0.8)              3 :  9464 (19.1%)       III                                        
                                                                                                     4 :  2254 ( 4.5%)                                                  

33   statecnt             Percent of sample from state               Mean (sd) : 6 (5.7)             57 distinct values        :                    50083      0        
     [numeric]                                                       min &lt; med &lt; max:                                          : .                  (100.0%)   (0.0%)   
                                                                     0 &lt; 3.5 &lt; 17.4                                          : : :             :                        
                                                                     IQR (CV) : 7.8 (1)                                      : : :     .       :                        
                                                                                                                             : : : :   :       :                        

34   stateresponse        Proportion of sample from the state who    Mean (sd) : 0 (0)               48 distinct values          :                  50083      0        
     [numeric]            gave                                       min &lt; med &lt; max:                                            :                  (100.0%)   (0.0%)   
                                                                     0 &lt; 0 &lt; 0.1                                                 :                                      
                                                                     IQR (CV) : 0 (0.3)                                          :                                      
                                                                                                                               . : :                                    

35   stateresponset       Proportion of treated sample from the      Mean (sd) : 0 (0)               47 distinct values        :                    50083      0        
     [numeric]            state who gave                             min &lt; med &lt; max:                                          :                    (100.0%)   (0.0%)   
                                                                     0 &lt; 0 &lt; 0.1                                               : .                                      
                                                                     IQR (CV) : 0 (0.3)                                        : :                                      
                                                                                                                               : :                                      

36   stateresponsec       Proportion of control sample from the      Mean (sd) : 0 (0)               41 distinct values          . :                50080      3        
     [numeric]            state who gave                             min &lt; med &lt; max:                                            : :                (100.0%)   (0.0%)   
                                                                     0 &lt; 0 &lt; 0.1                                                 : : .                                  
                                                                     IQR (CV) : 0 (0.4)                                          : : :                                  
                                                                                                                             :   : : : .                                

37   stateresponsetminc   stateresponset - stateresponsec            Mean (sd) : 0 (0)               49 distinct values            :                50080      3        
     [numeric]                                                       min &lt; med &lt; max:                                            . :                (100.0%)   (0.0%)   
                                                                     0 &lt; 0 &lt; 0.1                                                 : :                                    
                                                                     IQR (CV) : 0 (2.1)                                          : :                                    
                                                                                                                                 : : .                                  

38   perbush              State vote share for Bush                  Mean (sd) : 0.5 (0.1)           41 distinct values                :            50048      35       
     [numeric]                                                       min &lt; med &lt; max:                                                  : :          (99.9%)    (0.1%)   
                                                                     0.1 &lt; 0.5 &lt; 0.7                                                   : :                              
                                                                     IQR (CV) : 0.1 (0.2)                                            : : : :                            
                                                                                                                                     : : : : :                          

39   close25              State vote share for Bush between 47.5%    Min  : 0                        0 : 40754 (81.4%)       IIIIIIIIIIIIIIII       50048      35       
     [numeric]            and 52.5%                                  Mean : 0.2                      1 :  9294 (18.6%)       III                    (99.9%)    (0.1%)   
                                                                     Max  : 1                                                                                           

40   red0                 Red state                                  Min  : 0                        0 : 29806 (59.6%)       IIIIIIIIIII            50048      35       
     [numeric]                                                       Mean : 0.4                      1 : 20242 (40.4%)       IIIIIIII               (99.9%)    (0.1%)   
                                                                     Max  : 1                                                                                           

41   blue0                Blue state                                 Min  : 0                        0 : 20242 (40.4%)       IIIIIIII               50048      35       
     [numeric]                                                       Mean : 0.6                      1 : 29806 (59.6%)       IIIIIIIIIII            (99.9%)    (0.1%)   
                                                                     Max  : 1                                                                                           

42   redcty               Red county                                 Min  : 0                        0 : 24477 (49.0%)       IIIIIIIII              49978      105      
     [numeric]                                                       Mean : 0.5                      1 : 25501 (51.0%)       IIIIIIIIII             (99.8%)    (0.2%)   
                                                                     Max  : 1                                                                                           

43   bluecty              Blue county                                Min  : 0                        0 : 25553 (51.1%)       IIIIIIIIII             49978      105      
     [numeric]                                                       Mean : 0.5                      1 : 24425 (48.9%)       IIIIIIIII              (99.8%)    (0.2%)   
                                                                     Max  : 1                                                                                           

44   pwhite               Proportion white within zip code           Mean (sd) : 0.8 (0.2)           10729 distinct values                     :    48217      1866     
     [numeric]                                                       min &lt; med &lt; max:                                                        . :    (96.3%)    (3.7%)   
                                                                     0 &lt; 0.9 &lt; 1                                                             : :                        
                                                                     IQR (CV) : 0.2 (0.2)                                                  . : :                        
                                                                                                                                     . . : : : :                        

45   pblack               Proportion black within zip code           Mean (sd) : 0.1 (0.1)           10540 distinct values   :                      48047      2036     
     [numeric]                                                       min &lt; med &lt; max:                                        :                      (95.9%)    (4.1%)   
                                                                     0 &lt; 0 &lt; 1                                               :                                          
                                                                     IQR (CV) : 0.1 (1.6)                                    :                                          
                                                                                                                             : : .                                      

46   page18_39            Proportion age 18-39 within zip code       Mean (sd) : 0.3 (0.1)           10788 distinct values       : .                48217      1866     
     [numeric]                                                       min &lt; med &lt; max:                                            : :                (96.3%)    (3.7%)   
                                                                     0 &lt; 0.3 &lt; 1                                                 : :                                    
                                                                     IQR (CV) : 0.1 (0.3)                                        : : .                                  
                                                                                                                               : : : : .                                

47   ave_hh_sz            Average household size within zip code     Mean (sd) : 2.4 (0.4)           296 distinct values             :              48221      1862     
     [numeric]                                                       min &lt; med &lt; max:                                                :              (96.3%)    (3.7%)   
                                                                     0 &lt; 2.4 &lt; 5.3                                                   : .                                
                                                                     IQR (CV) : 0.5 (0.2)                                          . : :                                
                                                                                                                                   : : :                                

48   median_hhincome      Median household income within zip code    Mean (sd) : 54815.7 (22027.3)   9569 distinct values      : :                  48209      1874     
     [numeric]                                                       min &lt; med &lt; max:                                          : :                  (96.3%)    (3.7%)   
                                                                     5000 &lt; 50673 &lt; 200001                                     : : .                                    
                                                                     IQR (CV) : 26824 (0.4)                                    : : :                                    
                                                                                                                             . : : : : .                                

49   powner               Proportion house owner within zip code     Mean (sd) : 0.7 (0.2)           10794 distinct values                 : .      48214      1869     
     [numeric]                                                       min &lt; med &lt; max:                                                    . : :      (96.3%)    (3.7%)   
                                                                     0 &lt; 0.7 &lt; 1                                                       . : : :                          
                                                                     IQR (CV) : 0.3 (0.3)                                          . . : : : : .                        
                                                                                                                               . : : : : : : : :                        

50   psch_atlstba         Proportion who finished college within     Mean (sd) : 0.4 (0.2)           10790 distinct values     . : :                48215      1868     
     [numeric]            zip code                                   min &lt; med &lt; max:                                          : : : : .            (96.3%)    (3.7%)   
                                                                     0 &lt; 0.4 &lt; 1                                               : : : : : .                              
                                                                     IQR (CV) : 0.3 (0.5)                                      : : : : : : :                            
                                                                                                                             . : : : : : : :                            

51   pop_propurban        Proportion of population urban within      Mean (sd) : 0.9 (0.3)           5607 distinct values                      :    48217      1866     
     [numeric]            zip code                                   min &lt; med &lt; max:                                                          :    (96.3%)    (3.7%)   
                                                                     0 &lt; 1 &lt; 1                                                                 :                        
                                                                     IQR (CV) : 0.1 (0.3)                                                      :                        
                                                                                                                             .             . . :                        
------------------------------------------------------------------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>treatment</code></td>
<td>Treatment</td>
</tr>
<tr class="even">
<td><code>control</code></td>
<td>Control</td>
</tr>
<tr class="odd">
<td><code>ratio</code></td>
<td>Match ratio</td>
</tr>
<tr class="even">
<td><code>ratio2</code></td>
<td>2:1 match ratio</td>
</tr>
<tr class="odd">
<td><code>ratio3</code></td>
<td>3:1 match ratio</td>
</tr>
<tr class="even">
<td><code>size</code></td>
<td>Match threshold</td>
</tr>
<tr class="odd">
<td><code>size25</code></td>
<td>$25,000 match threshold</td>
</tr>
<tr class="even">
<td><code>size50</code></td>
<td>$50,000 match threshold</td>
</tr>
<tr class="odd">
<td><code>size100</code></td>
<td>$100,000 match threshold</td>
</tr>
<tr class="even">
<td><code>sizeno</code></td>
<td>Unstated match threshold</td>
</tr>
<tr class="odd">
<td><code>ask</code></td>
<td>Suggested donation amount</td>
</tr>
<tr class="even">
<td><code>askd1</code></td>
<td>Suggested donation was highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>askd2</code></td>
<td>Suggested donation was 1.25 x highest previous contribution</td>
</tr>
<tr class="even">
<td><code>askd3</code></td>
<td>Suggested donation was 1.50 x highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>ask1</code></td>
<td>Highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>ask2</code></td>
<td>1.25 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="odd">
<td><code>ask3</code></td>
<td>1.50 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>amount</code></td>
<td>Dollars given</td>
</tr>
<tr class="odd">
<td><code>gave</code></td>
<td>Gave anything</td>
</tr>
<tr class="even">
<td><code>amountchange</code></td>
<td>Change in amount given</td>
</tr>
<tr class="odd">
<td><code>hpa</code></td>
<td>Highest previous contribution</td>
</tr>
<tr class="even">
<td><code>ltmedmra</code></td>
<td>Small prior donor: last gift was less than median $35</td>
</tr>
<tr class="odd">
<td><code>freq</code></td>
<td>Number of prior donations</td>
</tr>
<tr class="even">
<td><code>years</code></td>
<td>Number of years since initial donation</td>
</tr>
<tr class="odd">
<td><code>year5</code></td>
<td>At least 5 years since initial donation</td>
</tr>
<tr class="even">
<td><code>mrm2</code></td>
<td>Number of months since last donation</td>
</tr>
<tr class="odd">
<td><code>dormant</code></td>
<td>Already donated in 2005</td>
</tr>
<tr class="even">
<td><code>female</code></td>
<td>Female</td>
</tr>
<tr class="odd">
<td><code>couple</code></td>
<td>Couple</td>
</tr>
<tr class="even">
<td><code>state50one</code></td>
<td>State tag: 1 for one observation of each of 50 states; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>nonlit</code></td>
<td>Nonlitigation</td>
</tr>
<tr class="even">
<td><code>cases</code></td>
<td>Court cases from state in 2004-5 in which organization was involved</td>
</tr>
<tr class="odd">
<td><code>statecnt</code></td>
<td>Percent of sample from state</td>
</tr>
<tr class="even">
<td><code>stateresponse</code></td>
<td>Proportion of sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponset</code></td>
<td>Proportion of treated sample from the state who gave</td>
</tr>
<tr class="even">
<td><code>stateresponsec</code></td>
<td>Proportion of control sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponsetminc</code></td>
<td>stateresponset - stateresponsec</td>
</tr>
<tr class="even">
<td><code>perbush</code></td>
<td>State vote share for Bush</td>
</tr>
<tr class="odd">
<td><code>close25</code></td>
<td>State vote share for Bush between 47.5% and 52.5%</td>
</tr>
<tr class="even">
<td><code>red0</code></td>
<td>Red state</td>
</tr>
<tr class="odd">
<td><code>blue0</code></td>
<td>Blue state</td>
</tr>
<tr class="even">
<td><code>redcty</code></td>
<td>Red county</td>
</tr>
<tr class="odd">
<td><code>bluecty</code></td>
<td>Blue county</td>
</tr>
<tr class="even">
<td><code>pwhite</code></td>
<td>Proportion white within zip code</td>
</tr>
<tr class="odd">
<td><code>pblack</code></td>
<td>Proportion black within zip code</td>
</tr>
<tr class="even">
<td><code>page18_39</code></td>
<td>Proportion age 18-39 within zip code</td>
</tr>
<tr class="odd">
<td><code>ave_hh_sz</code></td>
<td>Average household size within zip code</td>
</tr>
<tr class="even">
<td><code>median_hhincome</code></td>
<td>Median household income within zip code</td>
</tr>
<tr class="odd">
<td><code>powner</code></td>
<td>Proportion house owner within zip code</td>
</tr>
<tr class="even">
<td><code>psch_atlstba</code></td>
<td>Proportion who finished college within zip code</td>
</tr>
<tr class="odd">
<td><code>pop_propurban</code></td>
<td>Proportion of population urban within zip code</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="balance-test" class="level3">
<h3 class="anchored" data-anchor-id="balance-test">Balance Test</h3>
<p>As an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.</p>
<p>#<em>todo: test a few variables other than the key outcome variables (for example, test months since last donation) to see if the treatment and control groups are statistically significantly different at the 95% confidence level. Do each as a t-test and separately as a linear regression, and confirm you get the exact same results from both methods. When doing a t-test, use the formula in the class slides. When doing the linear regression, regress for example mrm2 on treatment and look at the estimated coefficient on the treatment variable. It might be helpful to compare parts of your analysis to Table 1 in the paper. Be sure to comment on your results (hint: why is Table 1 included in the paper).</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load dataset</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Split data by treatment</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>treat <span class="ot">&lt;-</span> <span class="fu">filter</span>(data, treatment <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>control <span class="ot">&lt;-</span> <span class="fu">filter</span>(data, treatment <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables to test</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"mrm2"</span>, <span class="st">"hpa"</span>, <span class="st">"freq"</span>,<span class="st">"page18_39"</span>,<span class="st">"red0"</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to report results</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (var <span class="cf">in</span> vars) {</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">==============================</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Variable:"</span>, var, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Means and SDs</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  treat_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(treat[[var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>  control_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(control[[var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>  treat_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(treat[[var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>  control_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(control[[var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>  overall_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(data[[var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>  overall_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(data[[var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Treatment Mean:"</span>, <span class="fu">round</span>(treat_mean, <span class="dv">3</span>), <span class="st">"SD:"</span>, <span class="fu">round</span>(treat_sd, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Control Mean:  "</span>, <span class="fu">round</span>(control_mean, <span class="dv">3</span>), <span class="st">"SD:"</span>, <span class="fu">round</span>(control_sd, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>  <span class="co"># T-test</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>  ttest <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="fu">as.formula</span>(<span class="fu">paste</span>(var, <span class="st">"~ treatment"</span>)), <span class="at">data =</span> data)</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"T-test p-value:"</span>, <span class="fu">round</span>(ttest<span class="sc">$</span>p.value, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Regression</span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>  model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">as.formula</span>(<span class="fu">paste</span>(var, <span class="st">"~ treatment"</span>)), <span class="at">data =</span> data)</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>  coef_summary <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"treatment"</span>)</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Regression Coefficient:"</span>, <span class="fu">round</span>(coef_summary<span class="sc">$</span>estimate, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Regression p-value:    "</span>, <span class="fu">round</span>(coef_summary<span class="sc">$</span>p.value, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
==============================
Variable: mrm2 
Treatment Mean: 13.012 SD: 12.086 
Control Mean:   12.998 SD: 12.074 
T-test p-value: 0.9049 
Regression Coefficient: 0.0137 
Regression p-value:     0.9049 

==============================
Variable: hpa 
Treatment Mean: 59.597 SD: 73.052 
Control Mean:   58.96 SD: 67.269 
T-test p-value: 0.3318 
Regression Coefficient: 0.6371 
Regression p-value:     0.3451 

==============================
Variable: freq 
Treatment Mean: 8.035 SD: 11.39 
Control Mean:   8.047 SD: 11.404 
T-test p-value: 0.9117 
Regression Coefficient: -0.012 
Regression p-value:     0.9117 

==============================
Variable: page18_39 
Treatment Mean: 0.322 SD: 0.103 
Control Mean:   0.322 SD: 0.103 
T-test p-value: 0.9011 
Regression Coefficient: -1e-04 
Regression p-value:     0.901 

==============================
Variable: red0 
Treatment Mean: 0.407 SD: 0.491 
Control Mean:   0.399 SD: 0.49 
T-test p-value: 0.0605 
Regression Coefficient: 0.0087 
Regression p-value:     0.0608 </code></pre>
</div>
</div>
<p>All tested variables show very similar means and standard deviations across treatment and control groups, as expected under successful randomization. The t-test and regression p-values are nearly identical and all above 0.05, indicating no statistically significant imbalance. These results replicate Table 1 in the Karlan &amp; List (2007) paper, which is included to show that randomization produced comparable groups on observable characteristics.</p>
</section>
</section>
<section id="experimental-results" class="level2">
<h2 class="anchored" data-anchor-id="experimental-results">Experimental Results</h2>
<section id="charitable-contribution-made" class="level3">
<h3 class="anchored" data-anchor-id="charitable-contribution-made">Charitable Contribution Made</h3>
<p>First, I analyze whether matched donations lead to an increased response rate of making a donation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate proportion who donated by treatment group</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>response_rate <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(treatment) <span class="sc">%&gt;%</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">proportion_donated =</span> <span class="fu">mean</span>(gave, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group =</span> <span class="fu">ifelse</span>(treatment <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Treatment"</span>, <span class="st">"Control"</span>))</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(response_rate, <span class="fu">aes</span>(<span class="at">x =</span> group, <span class="at">y =</span> proportion_donated, <span class="at">fill =</span> group)) <span class="sc">+</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Proportion of People Who Donated"</span>,</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion"</span>,</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">""</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fu">max</span>(response_rate<span class="sc">$</span>proportion_donated) <span class="sc">*</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>ttest_gave <span class="ot">&lt;-</span> <span class="fu">t.test</span>(gave <span class="sc">~</span> treatment, <span class="at">data =</span> data)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"T-test result:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T-test result:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ttest_gave)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  gave by treatment
t = -3.2095, df = 36577, p-value = 0.001331
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.006733310 -0.001627399
sample estimates:
mean in group 0 mean in group 1 
     0.01785821      0.02203857 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>model_gave <span class="ot">&lt;-</span> <span class="fu">lm</span>(gave <span class="sc">~</span> treatment, <span class="at">data =</span> data)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>reg_summary <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model_gave)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Linear regression result:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear regression result:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(reg_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)  0.0179    0.00110     16.2  4.78e-59
2 treatment    0.00418   0.00135      3.10 1.93e- 3</code></pre>
</div>
</div>
<p>The t-test comparing the proportion of individuals who made any charitable donation between the treatment and control groups shows a small but statistically significant increase in response rate in the treatment group. This confirms the finding in Table 2A, Panel A, where the response rate increases from 1.8% to 2.2% when matching is introduced.</p>
<p>The bivariate linear regression yields an equivalent result: the coefficient on <code>treatment</code> is positive and significant, indicating that simply offering a match increases the likelihood of donation.</p>
<p><strong>Interpretation:</strong> Even a small increase in donation probability — from just under 2% to just over 2% — is meaningful in a large fundraising campaign. This suggests that people are psychologically responsive to matching offers, even when the absolute value of the match is not very large. The perception of increased impact (“my $10 becomes $20”) may be enough to nudge more people into giving. This supports the idea that <strong>framing and context matter in charitable behavior</strong>, not just individual preferences.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(margins)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Probit regression: gave ~ treatment</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>probit_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(gave <span class="sc">~</span> treatment, <span class="at">data =</span> data, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>))</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the model</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(probit_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = gave ~ treatment, family = binomial(link = "probit"), 
    data = data)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.10014    0.02332 -90.074  &lt; 2e-16 ***
treatment    0.08678    0.02788   3.113  0.00185 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 10071  on 50082  degrees of freedom
Residual deviance: 10061  on 50081  degrees of freedom
AIC: 10065

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy output (for coefficient and SE)</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(probit_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)  -2.10      0.0233    -90.1  0      
2 treatment     0.0868    0.0279      3.11 0.00185</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional: Marginal effects (not required for Table 3, but helpful)</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>margins<span class="sc">::</span><span class="fu">margins</span>(probit_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Average marginal effects</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>glm(formula = gave ~ treatment, family = binomial(link = "probit"),     data = data)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> treatment
  0.004313</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model_full <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  gave <span class="sc">~</span> treatment <span class="sc">*</span> ratio2 <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>         treatment <span class="sc">*</span> ratio3 <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>         treatment <span class="sc">*</span> size25 <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>         treatment <span class="sc">*</span> size50 <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>         treatment <span class="sc">*</span> size100 <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>         treatment <span class="sc">*</span> askd2 <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>         treatment <span class="sc">*</span> askd3,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 5
   term              estimate std.error statistic p.value
   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1 (Intercept)       -2.10       0.0233  -90.1      0    
 2 treatment          0.0475     0.0496    0.958    0.338
 3 ratio2             0.0364     0.0377    0.967    0.334
 4 ratio3             0.0384     0.0376    1.02     0.308
 5 size25            -0.0117     0.0434   -0.270    0.787
 6 size50             0.00460    0.0431    0.107    0.915
 7 size100           -0.00221    0.0432   -0.0512   0.959
 8 askd2              0.0192     0.0377    0.509    0.611
 9 askd3              0.0293     0.0375    0.782    0.434
10 treatment:ratio2  NA         NA        NA       NA    
11 treatment:ratio3  NA         NA        NA       NA    
12 treatment:size25  NA         NA        NA       NA    
13 treatment:size50  NA         NA        NA       NA    
14 treatment:size100 NA         NA        NA       NA    
15 treatment:askd2   NA         NA        NA       NA    
16 treatment:askd3   NA         NA        NA       NA    </code></pre>
</div>
</div>
</section>
<section id="interpretation-of-probit-regression-result" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-probit-regression-result">Interpretation of Probit Regression Result</h3>
<p>The probit regression produced a positive and statistically significant coefficient on the treatment variable, with an estimated effect of <strong>0.0868</strong>, a z-value of <strong>3.11</strong>, and a p-value below <strong>0.01</strong>. This confirms that assignment to the treatment group — those who received a matching donation offer — was associated with a higher probability of making a donation.</p>
<p>The result is statistically significant at the <strong>1% level</strong>, providing strong evidence that the offer of a match influenced donor behavior. While the numerical value of the coefficient may seem modest, its significance within a nonlinear probit framework reinforces the idea that behavioral prompts like matching gifts can effectively shape outcomes.</p>
<p>In essence, this supports the broader finding from Karlan and List (2007): even relatively small psychological nudges can meaningfully impact decision-making in a real-world charitable context.</p>
</section>
<section id="differences-between-match-rates" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-match-rates">Differences between Match Rates</h3>
<p>Next, I assess the effectiveness of different sizes of matched donations on the response rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter only the people who were in a match group (i.e., treatment == 1)</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>matched <span class="ot">&lt;-</span> <span class="fu">filter</span>(data, treatment <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a variable for 1:1 match (implied if ratio2 and ratio3 are both 0)</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>matched <span class="ot">&lt;-</span> matched <span class="sc">%&gt;%</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio1 =</span> <span class="fu">ifelse</span>(ratio2 <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> ratio3 <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test: 2:1 match vs 1:1 match</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>t_21_vs_11 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(gave <span class="sc">~</span> ratio2, <span class="at">data =</span> <span class="fu">filter</span>(matched, ratio1 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> ratio2 <span class="sc">==</span> <span class="dv">1</span>))</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test: 3:1 match vs 1:1 match</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>t_31_vs_11 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(gave <span class="sc">~</span> ratio3, <span class="at">data =</span> <span class="fu">filter</span>(matched, ratio1 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> ratio3 <span class="sc">==</span> <span class="dv">1</span>))</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Output results</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"T-test: 2:1 vs 1:1 match rate</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T-test: 2:1 vs 1:1 match rate</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_21_vs_11)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  gave by ratio2
t = -0.96505, df = 22225, p-value = 0.3345
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.005711275  0.001942773
sample estimates:
mean in group 0 mean in group 1 
     0.02074912      0.02263338 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">T-test: 3:1 vs 1:1 match rate</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
T-test: 3:1 vs 1:1 match rate</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_31_vs_11)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  gave by ratio3
t = -1.015, df = 22215, p-value = 0.3101
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.005816051  0.001847501
sample estimates:
mean in group 0 mean in group 1 
     0.02074912      0.02273340 </code></pre>
</div>
</div>
</section>
<section id="effectiveness-of-different-match-ratios-t-test-results" class="level3">
<h3 class="anchored" data-anchor-id="effectiveness-of-different-match-ratios-t-test-results">Effectiveness of Different Match Ratios: T-Test Results</h3>
<p>To evaluate whether more generous match ratios (2:1 and 3:1) increase the likelihood of donating compared to the standard 1:1 match, I conducted two t-tests:</p>
<ul>
<li><strong>2:1 vs 1:1 match rate</strong></li>
<li><strong>3:1 vs 1:1 match rate</strong></li>
</ul>
<p>In both cases, the t-tests found <strong>no statistically significant difference</strong> in the probability of donation. The p-value for the 2:1 vs 1:1 comparison was <strong>0.3345</strong>, and for the 3:1 vs 1:1 comparison it was <strong>0.3101</strong> — both well above the conventional significance threshold of 0.05.</p>
<p>The estimated differences in means were very small, with confidence intervals that include zero, indicating no reliable effect of increasing the match ratio.</p>
<p>These results support the authors’ comment on page 8 of the paper that “<strong>larger match ratios had no additional impact</strong>.” In other words, donors respond to the <strong>presence</strong> of a match offer, but increasing the match from 1:1 to 2:1 or 3:1 does not lead to a higher response rate.</p>
<p>This finding reinforces a key insight from behavioral economics: <strong>perceived opportunity or framing (i.e., the existence of a match), rather than the size of the match, drives behavior</strong> in charitable giving contexts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset only treatment group (those who received any match)</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>matched <span class="ot">&lt;-</span> <span class="fu">filter</span>(data, treatment <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create ratio1 manually: it's the group not in ratio2 or ratio3</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>matched <span class="ot">&lt;-</span> matched <span class="sc">%&gt;%</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio1 =</span> <span class="fu">ifelse</span>(ratio2 <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> ratio3 <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Run regression with dummy variables (ratio1 is implicit baseline)</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>model_ratios <span class="ot">&lt;-</span> <span class="fu">lm</span>(gave <span class="sc">~</span> ratio2 <span class="sc">+</span> ratio3, <span class="at">data =</span> matched)</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Output tidy summary</span></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_ratios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)  0.0207    0.00139    14.9   3.98e-50
2 ratio2       0.00188   0.00197     0.958 3.38e- 1
3 ratio3       0.00198   0.00197     1.01  3.13e- 1</code></pre>
</div>
</div>
</section>
<section id="regression-analysis-impact-of-match-ratio-on-donation-behavior" class="level3">
<h3 class="anchored" data-anchor-id="regression-analysis-impact-of-match-ratio-on-donation-behavior">Regression Analysis: Impact of Match Ratio on Donation Behavior</h3>
<p>To assess whether the generosity of the match offer affects the likelihood of donating, I ran a linear regression using data from individuals who were in the treatment group. The model includes dummy variables for the 2:1 and 3:1 match offers, with the 1:1 match offer serving as the reference category.</p>
<p>The regression results show that: - The coefficient on <code>ratio2</code> is <strong>0.00188</strong> with a standard error of <strong>0.00197</strong>, and a p-value of <strong>0.338</strong>. - The coefficient on <code>ratio3</code> is <strong>0.00198</strong> with a standard error of <strong>0.00197</strong>, and a p-value of <strong>0.313</strong>.</p>
<p>These coefficients represent the difference in donation probability relative to the 1:1 match group. However, both coefficients are small and <strong>statistically insignificant</strong>, indicating that neither the 2:1 nor 3:1 match rate led to a meaningful increase in the likelihood of donating compared to a 1:1 match.</p>
<p>These findings are entirely consistent with earlier t-test results and support the authors’ conclusion that <strong>increasing the match ratio has no additional effect</strong>. The behavioral impact appears to stem from the presence of a match offer itself, rather than its magnitude. Donors may not be especially sensitive to whether the match is 1:1 or 3:1 — the idea of leverage seems to matter more than the amount.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only treatment group</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>matched <span class="ot">&lt;-</span> <span class="fu">filter</span>(data, treatment <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create 1:1 dummy</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>matched <span class="ot">&lt;-</span> matched <span class="sc">%&gt;%</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio1 =</span> <span class="fu">ifelse</span>(ratio2 <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> ratio3 <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="co"># ----- APPROACH 1: Direct from the data -----</span></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute response rates by match group</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>response_rates <span class="ot">&lt;-</span> matched <span class="sc">%&gt;%</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ratio_type =</span> <span class="fu">case_when</span>(</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>    ratio1 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"1:1"</span>,</span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>    ratio2 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"2:1"</span>,</span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>    ratio3 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"3:1"</span></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ratio_type) <span class="sc">%&gt;%</span></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">response_rate =</span> <span class="fu">mean</span>(gave, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract values for comparison</span></span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>rate_1_1 <span class="ot">&lt;-</span> response_rates<span class="sc">$</span>response_rate[response_rates<span class="sc">$</span>ratio_type <span class="sc">==</span> <span class="st">"1:1"</span>]</span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>rate_2_1 <span class="ot">&lt;-</span> response_rates<span class="sc">$</span>response_rate[response_rates<span class="sc">$</span>ratio_type <span class="sc">==</span> <span class="st">"2:1"</span>]</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>rate_3_1 <span class="ot">&lt;-</span> response_rates<span class="sc">$</span>response_rate[response_rates<span class="sc">$</span>ratio_type <span class="sc">==</span> <span class="st">"3:1"</span>]</span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate differences</span></span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a>diff_21_11 <span class="ot">&lt;-</span> rate_2_1 <span class="sc">-</span> rate_1_1</span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a>diff_31_21 <span class="ot">&lt;-</span> rate_3_1 <span class="sc">-</span> rate_2_1</span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a><span class="co"># ----- APPROACH 2: From regression coefficients -----</span></span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Run regression using 1:1 (ratio1) as the baseline</span></span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(gave <span class="sc">~</span> ratio2 <span class="sc">+</span> ratio3, <span class="at">data =</span> matched)</span>
<span id="cb40-40"><a href="#cb40-40" aria-hidden="true" tabindex="-1"></a>model_out <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model)</span>
<span id="cb40-41"><a href="#cb40-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-42"><a href="#cb40-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficient difference (they are relative to 1:1 group)</span></span>
<span id="cb40-43"><a href="#cb40-43" aria-hidden="true" tabindex="-1"></a>coef_21_11 <span class="ot">&lt;-</span> model_out<span class="sc">$</span>estimate[model_out<span class="sc">$</span>term <span class="sc">==</span> <span class="st">"ratio2"</span>]</span>
<span id="cb40-44"><a href="#cb40-44" aria-hidden="true" tabindex="-1"></a>coef_31_21 <span class="ot">&lt;-</span> model_out<span class="sc">$</span>estimate[model_out<span class="sc">$</span>term <span class="sc">==</span> <span class="st">"ratio3"</span>] <span class="sc">-</span> coef_21_11</span>
<span id="cb40-45"><a href="#cb40-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-46"><a href="#cb40-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Output results</span></span>
<span id="cb40-47"><a href="#cb40-47" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"== Response Rate Differences from Raw Data ==</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>== Response Rate Differences from Raw Data ==</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"2:1 - 1:1 ="</span>, <span class="fu">round</span>(diff_21_11, <span class="dv">5</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2:1 - 1:1 = 0.00188 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"3:1 - 2:1 ="</span>, <span class="fu">round</span>(diff_31_21, <span class="dv">5</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3:1 - 2:1 = 1e-04 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">== Differences in Fitted Coefficients ==</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
== Differences in Fitted Coefficients ==</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"2:1 vs 1:1 ="</span>, <span class="fu">round</span>(coef_21_11, <span class="dv">5</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2:1 vs 1:1 = 0.00188 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"3:1 vs 2:1 ="</span>, <span class="fu">round</span>(coef_31_21, <span class="dv">5</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3:1 vs 2:1 = 1e-04 </code></pre>
</div>
</div>
</section>
<section id="match-ratio-differences-response-rate-and-regression-analysis" class="level3">
<h3 class="anchored" data-anchor-id="match-ratio-differences-response-rate-and-regression-analysis">Match Ratio Differences: Response Rate and Regression Analysis</h3>
<p>To understand whether higher match ratios increase the likelihood of donation, I calculated response rate differences in two ways:</p>
<section id="differences-in-raw-response-rates" class="level4">
<h4 class="anchored" data-anchor-id="differences-in-raw-response-rates">1. Differences in Raw Response Rates</h4>
<ul>
<li><strong>2:1 vs 1:1</strong> match ratio: 0.00188</li>
<li><strong>3:1 vs 2:1</strong> match ratio: 0.00010</li>
</ul>
</section>
<section id="differences-in-fitted-coefficients-linear-model" class="level4">
<h4 class="anchored" data-anchor-id="differences-in-fitted-coefficients-linear-model">2. Differences in Fitted Coefficients (Linear Model)</h4>
<ul>
<li><strong>2:1 vs 1:1</strong>: 0.00188</li>
<li><strong>3:1 vs 2:1</strong>: 0.00010</li>
</ul>
<p>Both approaches yielded the <strong>same differences</strong>, confirming that the estimated impact of increasing the match ratio is extremely small — around <strong>0.1 to 0.2 percentage points</strong>.</p>
</section>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>These findings provide strong evidence that increasing the match ratio from 1:1 to 2:1 or from 2:1 to 3:1 does <strong>not significantly increase</strong> the probability that someone donates.</p>
<p>This aligns with the authors’ conclusion: the <strong>presence of a match offer</strong>, rather than its <strong>generosity</strong>, is what motivates donations. Donors respond to the idea of a match, but <strong>larger matches do not provide additional behavioral lift</strong>.</p>
<p>In sum, the marginal effectiveness of more generous matches is negligible — a key insight for fundraisers seeking efficient campaign strategies.</p>
</section>
<section id="size-of-charitable-contribution" class="level3">
<h3 class="anchored" data-anchor-id="size-of-charitable-contribution">Size of Charitable Contribution</h3>
<p>In this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test: Compare average donation amount</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>t_test_amount <span class="ot">&lt;-</span> <span class="fu">t.test</span>(amount <span class="sc">~</span> treatment, <span class="at">data =</span> data)</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"== T-test: Donation Amount by Treatment Status ==</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>== T-test: Donation Amount by Treatment Status ==</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test_amount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  amount by treatment
t = -1.9183, df = 36216, p-value = 0.05509
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.310555423  0.003344493
sample estimates:
mean in group 0 mean in group 1 
      0.8132678       0.9668733 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression: Amount ~ Treatment</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>model_amount <span class="ot">&lt;-</span> <span class="fu">lm</span>(amount <span class="sc">~</span> treatment, <span class="at">data =</span> data)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">== Linear Regression: Amount ~ Treatment ==</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
== Linear Regression: Amount ~ Treatment ==</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_amount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)    0.813    0.0674     12.1  1.84e-33
2 treatment      0.154    0.0826      1.86 6.28e- 2</code></pre>
</div>
</div>
</section>
<section id="effect-of-match-offers-on-donation-amounts" class="level3">
<h3 class="anchored" data-anchor-id="effect-of-match-offers-on-donation-amounts">Effect of Match Offers on Donation Amounts</h3>
<p>To assess whether being offered a matching donation opportunity affects the amount individuals donate, I conducted both a t-test and a bivariate linear regression using the full dataset.</p>
<p>The <strong>t-test</strong> comparing average donation amounts between treatment and control groups yielded a <strong>p-value of 0.055</strong>, which is just above the traditional 5% significance threshold. The average donation was $0.81 in the control group and $0.97 in the treatment group — a difference of approximately $0.15.</p>
<p>The <strong>linear regression</strong> of donation amount on treatment status produced a coefficient of <strong>0.154</strong> with a <strong>p-value of 0.0628</strong>, again marginally above the 5% threshold. This suggests a small, positive effect of treatment on donation amount, but not strong enough to be deemed statistically significant at conventional levels.</p>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>These results indicate that <strong>being offered a match may slightly increase the average amount donated</strong>, but the evidence is not strong enough to make a confident causal claim. The p-values suggest that the observed difference might be due to chance, though the direction of the effect (positive) is consistent with the broader narrative of the study.</p>
<p>In summary, while matching offers clearly increase the likelihood that someone donates, the evidence that they increase the <strong>size</strong> of the donation (unconditionally) is <strong>suggestive but not definitive</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to donors only (those who gave something)</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>donors_only <span class="ot">&lt;-</span> <span class="fu">filter</span>(data, gave <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test: Compare average amount given among donors</span></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>t_test_donors <span class="ot">&lt;-</span> <span class="fu">t.test</span>(amount <span class="sc">~</span> treatment, <span class="at">data =</span> donors_only)</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"== T-test: Donation Amount by Treatment Status (Donors Only) ==</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>== T-test: Donation Amount by Treatment Status (Donors Only) ==</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test_donors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  amount by treatment
t = 0.58461, df = 557.46, p-value = 0.559
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -3.937240  7.274027
sample estimates:
mean in group 0 mean in group 1 
       45.54027        43.87188 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression: Amount ~ Treatment (among donors)</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>model_donors <span class="ot">&lt;-</span> <span class="fu">lm</span>(amount <span class="sc">~</span> treatment, <span class="at">data =</span> donors_only)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">== Linear Regression: Amount ~ Treatment (Donors Only) ==</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
== Linear Regression: Amount ~ Treatment (Donors Only) ==</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_donors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)    45.5       2.42    18.8   5.47e-68
2 treatment      -1.67      2.87    -0.581 5.61e- 1</code></pre>
</div>
</div>
</section>
<section id="conditional-effect-of-treatment-on-donation-amount-among-donors-only" class="level3">
<h3 class="anchored" data-anchor-id="conditional-effect-of-treatment-on-donation-amount-among-donors-only">Conditional Effect of Treatment on Donation Amount (Among Donors Only)</h3>
<p>To examine whether match offers influenced how much people donated — conditional on having donated — I restricted the dataset to only those individuals who gave a positive amount.</p>
<section id="t-test-results" class="level4">
<h4 class="anchored" data-anchor-id="t-test-results">T-Test Results</h4>
<p>The average donation among the <strong>control group</strong> was <strong>$45.54</strong>, while the average in the <strong>treatment group</strong> was <strong>$43.87</strong>. The t-test revealed <strong>no statistically significant difference</strong> between the two groups (p = 0.559). The 95% confidence interval for the difference in means includes zero, reinforcing this conclusion.</p>
</section>
<section id="regression-results" class="level4">
<h4 class="anchored" data-anchor-id="regression-results">Regression Results</h4>
<p>The linear regression of donation amount on treatment (among donors only) produced a coefficient of <strong>-1.67</strong>, indicating that those in the treatment group donated slightly less on average. However, the effect is <strong>not statistically significant</strong> (p = 0.561).</p>
</section>
<section id="interpretation-and-causal-insights" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-causal-insights">Interpretation and Causal Insights</h4>
<p>These results suggest that <strong>being offered a match does not influence the size of the donation</strong>, once someone has decided to donate. In fact, if anything, treated individuals gave slightly <strong>less</strong>, though the difference is not meaningful.</p>
<p>Importantly, <strong>this analysis is conditional on donation behavior</strong>, which was itself affected by the treatment. Because we are conditioning on a <strong>post-treatment variable</strong> (gave), the regression coefficient <strong>does not have a causal interpretation</strong>. The group of donors in the treatment group may differ in unobservable ways from donors in the control group, and this could bias the estimate.</p>
<p>In summary, this analysis tells us that the <strong>treatment affects the extensive margin (whether people give), not the intensive margin (how much they give)</strong> — a conclusion that aligns with the broader findings of Karlan and List (2007).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to donors only</span></span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> <span class="fu">filter</span>(data, gave <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate group means</span></span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a>group_means <span class="ot">&lt;-</span> donors <span class="sc">%&gt;%</span></span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(treatment) <span class="sc">%&gt;%</span></span>
<span id="cb68-14"><a href="#cb68-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_amount =</span> <span class="fu">mean</span>(amount, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb68-15"><a href="#cb68-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-16"><a href="#cb68-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for Treatment Group</span></span>
<span id="cb68-17"><a href="#cb68-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">filter</span>(donors, treatment <span class="sc">==</span> <span class="dv">1</span>), <span class="fu">aes</span>(<span class="at">x =</span> amount)) <span class="sc">+</span></span>
<span id="cb68-18"><a href="#cb68-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb68-19"><a href="#cb68-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> group_means<span class="sc">$</span>mean_amount[group_means<span class="sc">$</span>treatment <span class="sc">==</span> <span class="dv">1</span>],</span>
<span id="cb68-20"><a href="#cb68-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb68-21"><a href="#cb68-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb68-22"><a href="#cb68-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Donation Amounts (Treatment Group)"</span>,</span>
<span id="cb68-23"><a href="#cb68-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Amount Donated"</span>,</span>
<span id="cb68-24"><a href="#cb68-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb68-25"><a href="#cb68-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb68-26"><a href="#cb68-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for Control Group</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">filter</span>(donors, treatment <span class="sc">==</span> <span class="dv">0</span>), <span class="fu">aes</span>(<span class="at">x =</span> amount)) <span class="sc">+</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"lightgreen"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> group_means<span class="sc">$</span>mean_amount[group_means<span class="sc">$</span>treatment <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Donation Amounts (Control Group)"</span>,</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Amount Donated"</span>,</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="donation-amount-distributions-treatment-vs.-control-donors-only" class="level3">
<h3 class="anchored" data-anchor-id="donation-amount-distributions-treatment-vs.-control-donors-only">Donation Amount Distributions: Treatment vs.&nbsp;Control (Donors Only)</h3>
<p>The two histograms above show the distribution of donation amounts among individuals who made a donation, separated by treatment assignment. The red vertical line in each plot marks the <strong>average donation amount</strong> within that group.</p>
<ul>
<li>In the <strong>treatment group</strong>, the distribution of donations is right-skewed, with most donations falling between $10 and $100. The average donation is just below $44.</li>
<li>In the <strong>control group</strong>, the pattern is similar, though the average donation is slightly higher, around $45.5.</li>
</ul>
<p>Visually, the distributions are quite similar. Both groups show large clustering at common donation levels (e.g., $25, $50, $100), suggesting donors may be responding to standard ask amounts or psychological anchors.</p>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">Interpretation</h3>
<p>These plots support the earlier statistical analysis: <strong>being offered a match does not appear to increase the average amount donated among those who give</strong>. In fact, the average donation is marginally lower in the treatment group. However, this difference is not statistically significant, and the shapes of the two distributions are nearly identical.</p>
<p>This visualization reinforces the paper’s broader conclusion that matching gifts increase the <strong>likelihood of giving</strong>, but <strong>not the size</strong> of the donation once that decision has been made. The behavioral nudge seems to influence the extensive margin (give vs.&nbsp;not give), not the intensive margin (how much to give).</p>
</section>
</section>
<section id="simulation-experiment" class="level2">
<h2 class="anchored" data-anchor-id="simulation-experiment">Simulation Experiment</h2>
<p>As a reminder of how the t-statistic “works,” in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.</p>
<p>Suppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made.</p>
<p>Further suppose that the true distribution of respondents who do get a charitable donation match of any size is Bernoulli with probability p=0.022 that a donation is made.</p>
<section id="law-of-large-numbers" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers">Law of Large Numbers</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 100,000 control group donations (mean = 0.813, sd = 10)</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>control <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100000</span>, <span class="at">mean =</span> <span class="fl">0.813</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 10,000 treatment group donations (mean = 0.966, sd = 10)</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>treatment <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10000</span>, <span class="at">mean =</span> <span class="fl">0.966</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate 10,000 differences (each treatment value - sampled control value)</span></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>diffs <span class="ot">&lt;-</span> treatment <span class="sc">-</span> <span class="fu">sample</span>(control, <span class="at">size =</span> <span class="dv">10000</span>)</span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute cumulative average</span></span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a>cum_avg <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(diffs) <span class="sc">/</span> <span class="fu">seq_along</span>(diffs)</span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-16"><a href="#cb71-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data for plotting</span></span>
<span id="cb71-17"><a href="#cb71-17" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb71-18"><a href="#cb71-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>,</span>
<span id="cb71-19"><a href="#cb71-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">cum_avg =</span> cum_avg</span>
<span id="cb71-20"><a href="#cb71-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb71-21"><a href="#cb71-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-22"><a href="#cb71-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the convergence</span></span>
<span id="cb71-23"><a href="#cb71-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb71-24"><a href="#cb71-24" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> cum_avg)) <span class="sc">+</span></span>
<span id="cb71-25"><a href="#cb71-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.8</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb71-26"><a href="#cb71-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(treatment) <span class="sc">-</span> <span class="fu">mean</span>(control), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb71-27"><a href="#cb71-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)) <span class="sc">+</span>  <span class="co"># focus the Y-axis for cleaner view</span></span>
<span id="cb71-28"><a href="#cb71-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb71-29"><a href="#cb71-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Cumulative Average of Treatment-Control Differences"</span>,</span>
<span id="cb71-30"><a href="#cb71-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Simulating the Law of Large Numbers"</span>,</span>
<span id="cb71-31"><a href="#cb71-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Sample Size"</span>,</span>
<span id="cb71-32"><a href="#cb71-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Cumulative Average Difference"</span></span>
<span id="cb71-33"><a href="#cb71-33" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb71-34"><a href="#cb71-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="simulating-the-law-of-large-numbers" class="level3">
<h3 class="anchored" data-anchor-id="simulating-the-law-of-large-numbers">Simulating the Law of Large Numbers</h3>
<p>The plot above shows the cumulative average of 10,000 differences between randomly drawn treatment and control values. Specifically, we simulate 100,000 values from the control distribution and 10,000 from the treatment distribution, then compute the difference in means one pair at a time. The blue line shows the evolving average of those differences as the sample size increases.</p>
<p>At the beginning of the plot, we see high variability — the cumulative average fluctuates wildly with the first few draws. This reflects the influence of <strong>random noise</strong> when the sample size is small. However, as the number of observations increases, the cumulative average begins to <strong>stabilize</strong>, eventually converging toward the red dashed line, which represents the <strong>true difference in means</strong> between the treatment and control groups.</p>
<p>This behavior is a textbook demonstration of the <strong>Law of Large Numbers</strong>: as sample size increases, the sample average becomes a more accurate estimate of the population average. In practical terms, it tells us that while individual comparisons may be noisy, large samples can reveal reliable patterns. Here, the cumulative average confirms the treatment group tends to donate more than the control group — and that this effect emerges clearly as sample size grows.</p>
</section>
<section id="central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="central-limit-theorem">Central Limit Theorem</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate sampling distribution of differences</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>simulate_diff_means <span class="ot">&lt;-</span> <span class="cf">function</span>(n, <span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">mu_c =</span> <span class="fl">0.813</span>, <span class="at">mu_t =</span> <span class="fl">0.966</span>, <span class="at">sd =</span> <span class="dv">10</span>) {</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  diffs <span class="ot">&lt;-</span> <span class="fu">replicate</span>(reps, {</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(<span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu_t, <span class="at">sd =</span> sd)) <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu_c, <span class="at">sd =</span> sd))</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">diff =</span> diffs, <span class="at">sample_size =</span> <span class="fu">paste0</span>(<span class="st">"n = "</span>, n))</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate datasets</span></span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a>sizes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">200</span>, <span class="dv">500</span>, <span class="dv">1000</span>)</span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(sizes, simulate_diff_means))</span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histograms</span></span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sim_data, <span class="fu">aes</span>(<span class="at">x =</span> diff)) <span class="sc">+</span></span>
<span id="cb72-20"><a href="#cb72-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb72-21"><a href="#cb72-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>sample_size, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb72-22"><a href="#cb72-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb72-23"><a href="#cb72-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb72-24"><a href="#cb72-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Sampling Distribution of Differences in Means"</span>,</span>
<span id="cb72-25"><a href="#cb72-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Simulated at Varying Sample Sizes"</span>,</span>
<span id="cb72-26"><a href="#cb72-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Difference in Means (Treatment - Control)"</span>,</span>
<span id="cb72-27"><a href="#cb72-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb72-28"><a href="#cb72-28" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb72-29"><a href="#cb72-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sampling-distributions-at-different-sample-sizes" class="level3">
<h3 class="anchored" data-anchor-id="sampling-distributions-at-different-sample-sizes">Sampling Distributions at Different Sample Sizes</h3>
<p>The four histograms above show the <strong>sampling distribution of the difference in means</strong> between treatment and control groups at sample sizes of 50, 200, 500, and 1000. Each plot represents 1,000 simulations where, for each simulation, we draw <code>n</code> observations from each group, compute their sample means, and record the difference.</p>
<ul>
<li><p>At <strong>n = 50</strong>, the distribution is wide and noisy, with a substantial spread. In this case, <strong>zero is near the center</strong> of the distribution, meaning we would often observe a difference close to zero just by chance.</p></li>
<li><p>At <strong>n = 200</strong>, the distribution is more concentrated, though still displays some variability. <strong>Zero is still within the range of plausible outcomes</strong>, but less frequently near the center.</p></li>
<li><p>At <strong>n = 500</strong>, the sampling distribution narrows significantly, and <strong>zero starts to move toward the edge</strong> of the distribution — suggesting stronger evidence of a real difference.</p></li>
<li><p>At <strong>n = 1000</strong>, the distribution is tight and centered around the true mean difference. <strong>Zero is now well into the tails</strong>, meaning it’s unlikely we would observe a difference this close to zero if the treatment and control distributions were truly the same.</p></li>
</ul>
</section>
<section id="what-we-learn" class="level3">
<h3 class="anchored" data-anchor-id="what-we-learn">What We Learn</h3>
<p>These plots visually demonstrate the <strong>power of larger sample sizes</strong>. As the sample size increases: - The <strong>sampling variability decreases</strong> - The <strong>sampling distribution becomes more precise</strong> - We are better able to detect small true differences in population means</p>
<p>This is a direct illustration of the <strong>Central Limit Theorem</strong> and the <strong>Law of Large Numbers</strong> in action. At larger sample sizes, we can distinguish signal from noise more effectively — and zero becomes an unlikely outcome when a real treatment effect exists.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>